CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT DEFAULT '',image TEXT DEFAULT '',stock INTEGER DEFAULT 0,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS product_sizes (id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,size_name TEXT NOT NULL,price INTEGER NOT NULL,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT NOT NULL,governorate TEXT NOT NULL,address TEXT NOT NULL,items_json TEXT NOT NULL,total INTEGER NOT NULL,status TEXT DEFAULT 'new',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,product TEXT NOT NULL,rating INTEGER NOT NULL,comment TEXT NOT NULL,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS coupons (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,type TEXT NOT NULL,value INTEGER NOT NULL,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shipping (governorate TEXT PRIMARY KEY,price INTEGER NOT NULL);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('القاهرة',80);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الجيزة',80);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الإسكندرية',90);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('القليوبية',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الشرقية',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الدقهلية',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الغربية',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('المنوفية',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('كفر الشيخ',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('دمياط',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('البحيرة',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الإسماعيلية',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('السويس',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('بورسعيد',85);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الفيوم',100);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('بني سويف',100);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('المنيا',110);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('أسيوط',110);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('سوهاج',125);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('قنا',125);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الأقصر',130);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('أسوان',130);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('الوادي الجديد',120);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('مرسى مطروح',130);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('شمال سيناء',140);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('جنوب سيناء',140);
INSERT OR IGNORE INTO shipping(governorate,price) VALUES('البحر الأحمر',140);
INSERT OR IGNORE INTO settings(key,value) VALUES('whatsapp','201116186020');
