name = "laithe-parfums"
main = "src/index.js"
compatibility_date = "2026-08-17"

[assets]
directory = "./public"

[[d1_databases]]
binding = "LAITHE_DB"
database_name = "laithe-parfums-db"
database_id = "d638bfd1-2722-4b52-bf1f-87d8fb80782d"
