const cors = {"Access-Control-Allow-Origin":"same-origin","Access-Control-Allow-Credentials":"true"};
function json(x,status=200,extra={}){return new Response(JSON.stringify(x),{status,headers:{"Content-Type":"application/json",...cors,...extra}})}
function cookie(name,value,maxAge=86400){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function hash(s){const b=new TextEncoder().encode(s);const h=await crypto.subtle.digest("SHA-256",b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function auth(req,env){const c=req.headers.get('Cookie')||'';const m=c.match(/LAITHE_SESSION=([^;]+)/);if(!m)return false;return m[1]===await hash(`${env.ADMIN_EMAIL}:${env.ADMIN_PASSWORD}:${env.SESSION_SECRET}`)}
async function requireAuth(req,env){return await auth(req,env)}
async function body(req){try{return await req.json()}catch{return {}}}
async function api(req,env,path){
 if(path==='/store'&&req.method==='GET'){
   if(!env.LAITHE_DB)return json({products:[],settings:{whatsapp:'201116186020'}});
   const r=await env.LAITHE_DB.prepare(`SELECT p.id,p.name,p.category,p.description,p.image,p.stock,COALESCE(json_group_array(CASE WHEN s.id IS NULL THEN NULL ELSE json_object('id',s.id,'name',s.size_name,'price',s.price) END),'[]') sizes FROM products p LEFT JOIN product_sizes s ON s.product_id=p.id WHERE p.active=1 GROUP BY p.id ORDER BY p.id DESC`).all();
   const settings=await env.LAITHE_DB.prepare("SELECT key,value FROM settings").all();
   return json({products:r.results.map(p=>({...p,sizes:JSON.parse(p.sizes).filter(Boolean)})),settings:Object.fromEntries(settings.results.map(x=>[x.key,x.value]))});
 }
 if(path==='/reviews'&&req.method==='GET'){const r=await env.LAITHE_DB.prepare("SELECT name,product,rating,comment FROM reviews WHERE status='approved' ORDER BY id DESC").all();return json(r.results)}
 if(path==='/reviews'&&req.method==='POST'){const b=await body(req);if(!b.name||!b.product||!b.comment||b.rating<1||b.rating>5)return json({error:'invalid'},400);await env.LAITHE_DB.prepare("INSERT INTO reviews(name,product,rating,comment,status) VALUES(?,?,?,?, 'pending')").bind(b.name,b.product,b.rating,b.comment).run();return json({ok:true})}
 if(path==='/orders'&&req.method==='POST'){const b=await body(req);if(!b.name||!b.phone||!b.governorate||!b.address||!Array.isArray(b.items)||!b.items.length)return json({error:'invalid'},400);let total=b.items.reduce((a,x)=>a+(+x.price||0)*(+x.qty||1),0);const sh=await env.LAITHE_DB.prepare("SELECT price FROM shipping WHERE governorate=?").bind(b.governorate).first();const shipping=sh?.price||0;let r=await env.LAITHE_DB.prepare("INSERT INTO orders(name,phone,governorate,address,items_json,total,status) VALUES(?,?,?,?,?,?,?)").bind(b.name,b.phone,b.governorate,b.address,JSON.stringify(b.items),total+shipping,'new').run();return json({id:r.meta.last_row_id,total:total+shipping,shipping})}
 if(path==='/admin/login'&&req.method==='POST'){const b=await body(req);if(!env.ADMIN_EMAIL||!env.ADMIN_PASSWORD||b.email!==env.ADMIN_EMAIL||b.password!==env.ADMIN_PASSWORD)return json({error:'unauthorized'},401);const token=await hash(`${env.ADMIN_EMAIL}:${env.ADMIN_PASSWORD}:${env.SESSION_SECRET}`);return json({ok:true},{headers:{"Set-Cookie":cookie('LAITHE_SESSION',token,86400*7)}})}
 if(path==='/admin/logout'&&req.method==='POST')return json({ok:true},{headers:{"Set-Cookie":cookie('LAITHE_SESSION','',0)}})
 if(path==='/admin/me'&&req.method==='GET')return auth(req,env)?json({ok:true}):json({error:'unauthorized'},401)
 if(path.startsWith('/admin/')){
   if(!await requireAuth(req,env))return json({error:'unauthorized'},401);
   if(path==='/admin/data'){const [p,o,c,r,s,sh]=await Promise.all([env.LAITHE_DB.prepare("SELECT * FROM products ORDER BY id DESC").all(),env.LAITHE_DB.prepare("SELECT * FROM orders ORDER BY id DESC").all(),env.LAITHE_DB.prepare("SELECT * FROM coupons ORDER BY id DESC").all(),env.LAITHE_DB.prepare("SELECT * FROM reviews ORDER BY id DESC").all(),env.LAITHE_DB.prepare("SELECT key,value FROM settings").all(),env.LAITHE_DB.prepare("SELECT * FROM shipping ORDER BY governorate").all()]);for(const x of p.results)x.sizes=(await env.LAITHE_DB.prepare("SELECT id,size_name AS name,price FROM product_sizes WHERE product_id=?").bind(x.id).all()).results;return json({products:p.results,orders:o.results,coupons:c.results,reviews:r.results,settings:Object.fromEntries(s.results.map(x=>[x.key,x.value])),shipping:sh.results})}
   if(path==='/admin/products'){const b=await body(req);if(req.method==='POST'){let r=await env.LAITHE_DB.prepare("INSERT INTO products(name,category,description,image,stock,active) VALUES(?,?,?,?,?,1)").bind(b.name,b.category,b.description||'',b.image||'',b.stock||0).run();for(const s of b.sizes||[])await env.LAITHE_DB.prepare("INSERT INTO product_sizes(product_id,size_name,price) VALUES(?,?,?)").bind(r.meta.last_row_id,s.name,s.price).run();return json({ok:true})}if(req.method==='PUT'){await env.LAITHE_DB.prepare("UPDATE products SET name=?,category=?,description=?,image=?,stock=? WHERE id=?").bind(b.name,b.category,b.description||'',b.image||'',b.stock||0,b.id).run();await env.LAITHE_DB.prepare("DELETE FROM product_sizes WHERE product_id=?").bind(b.id).run();for(const s of b.sizes||[])await env.LAITHE_DB.prepare("INSERT INTO product_sizes(product_id,size_name,price) VALUES(?,?,?)").bind(b.id,s.name,s.price).run();return json({ok:true})}if(req.method==='DELETE'){await env.LAITHE_DB.prepare("DELETE FROM products WHERE id=?").bind(b.id).run();return json({ok:true})}}
   if(path==='/admin/orders'&&req.method==='PUT'){const b=await body(req);await env.LAITHE_DB.prepare("UPDATE orders SET status=? WHERE id=?").bind(b.status,b.id).run();return json({ok:true})}
   if(path==='/admin/reviews'&&req.method==='PUT'){const b=await body(req);await env.LAITHE_DB.prepare("UPDATE reviews SET status=? WHERE id=?").bind(b.status,b.id).run();return json({ok:true})}
   if(path==='/admin/coupons'&&req.method==='POST'){const b=await body(req);await env.LAITHE_DB.prepare("INSERT INTO coupons(code,type,value,active) VALUES(?,?,?,1)").bind(b.code,b.type,b.value).run();return json({ok:true})}
   if(path==='/admin/shipping'&&req.method==='PUT'){const b=await body(req);await env.LAITHE_DB.prepare("INSERT INTO shipping(governorate,price) VALUES(?,?) ON CONFLICT(governorate) DO UPDATE SET price=excluded.price").bind(b.governorate,b.price).run();return json({ok:true})}
   if(path==='/admin/settings'&&req.method==='PUT'){const b=await body(req);for(const [k,v] of Object.entries(b))await env.LAITHE_DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(k,String(v)).run();return json({ok:true})}
 }
 return null
}
export default {async fetch(req,env){const u=new URL(req.url);if(u.pathname.startsWith('/api/'))return (await api(req,env,u.pathname.slice(4)))||json({error:'not found'},404);return env.ASSETS.fetch(req)}}
